name: 'Artifact Helper'
description: '产物管理辅助 Action'
author: 'GitHub Action Builder'

inputs:
  action:
    description: '操作类型（upload/download）'
    required: true
  name:
    description: '产物名称'
    required: true
  path:
    description: '产物路径（upload 时）或目标路径（download 时）'
    required: false
    default: 'artifacts/**'

runs:
  using: 'composite'
  steps:
    - name: Upload artifact
      if: ${{ inputs.action == 'upload' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        retention-days: 30
    
    - name: Download artifact
      if: ${{ inputs.action == 'download' }}
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}


