name: 'Build Action'
description: '标准化构建流程 Action'
author: 'GitHub Action Builder'

inputs:
  build-command:
    description: '构建命令'
    required: true
  setup-command:
    description: '环境设置命令（如安装依赖）'
    required: false
    default: ''
  artifact-path:
    description: '构建产物路径'
    required: false
    default: 'artifacts/**'
  build-type:
    description: '构建类型（debug/release）'
    required: false
    default: 'release'
  upload-artifacts:
    description: '是否上传构建产物'
    required: false
    default: 'true'

outputs:
  build-status:
    description: '构建状态'
  artifact-path:
    description: '产物路径'
  build-type:
    description: '构建类型'

runs:
  using: 'node20'
  main: 'dist/index.js'


